# Generated by Django 6.0.5 on 2026-05-06 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transaction_created_at_transaction_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Account',
        ),
    ]
