# Generated by Django 6.0.5 on 2026-05-07 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_transaction_delete_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transactions_type',
            new_name='transaction_type',
        ),
    ]
