# Generated by Django 6.0.5 on 2026-05-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_transactions_type_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('ALKANSYA', 'Alkansya'), ('BALANCE_ADJUSTMENT', 'Balance Adjustment'), ('BUSINESS', 'Business'), ('CASHBACK', 'Cashback'), ('COMPANY_BONUS', 'Company Bonus'), ('CONTENT_CREATION', 'Content Creation'), ('DIVIDENDS', 'Dividends'), ('FREELANCE', 'Freelance'), ('INTEREST', 'Interest'), ('INVESTMENT', 'Investment'), ('REMITTANCE', 'Remittance'), ('SALARY', 'Salary'), ('SIDE_HUSTLE', 'Side Hustle'), ('CHURCH', 'Church'), ('FAMILY_SUPPORT', 'Family Support'), ('FOOD_AND_DRINKS', 'Food and Drinks'), ('GIFTS', 'Gifts'), ('GROCERY', 'Grocery'), ('HEALTH', 'Health'), ('HOUSE_BILLS', 'House Bills'), ('ONLINE_SHOPPING', 'Online Shopping'), ('PETS', 'Pets'), ('RENT', 'Rent'), ('SCHOOL', 'School'), ('SUBSCRIPTIONS', 'Subscriptions'), ('TRANSPORTATION', 'Transportation'), ('TRAVEL', 'Travel'), ('UTILITIES', 'Utilities')], max_length=30),
        ),
    ]
