# Generated by Django 6.0.5 on 2026-05-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_category_transaction_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='source',
            field=models.CharField(choices=[('ATOME', 'Atome'), ('AUB', 'AUB'), ('BANKO', 'Banko'), ('BANKOFCOMMERCE', 'Bank of Commerce'), ('BANKOFMAKATI', 'Bank of Makati'), ('BDO', 'BDO'), ('BEEP', 'Beep'), ('BILLEASE', 'BillEase'), ('BPI', 'BPI'), ('CASH', 'Cash'), ('CASHALO', 'Cashalo'), ('CBS', 'CBS'), ('CEBUANA', 'Cebuana'), ('CHINABANK', 'Chinabank'), ('CIMB', 'CIMB'), ('CTBC', 'CTBC'), ('DBP', 'DBP'), ('DISKARTECH', 'DiskarTech'), ('EASTWEST', 'EastWest'), ('FOODPANDA', 'Foodpanda'), ('GCASH', 'GCash'), ('GOTYME', 'GoTyme'), ('GRAB', 'Grab'), ('HELLOMONEY', 'HelloMoney'), ('HOMECREDIT', 'Home Credit'), ('HSBC', 'HSBC'), ('JOYRIDE', 'JoyRide'), ('JUANHAND', 'JuanHand'), ('KOMO', 'Komo'), ('LANDBANK', 'Landbank'), ('LAZADA', 'Lazada'), ('MARCOPAY', 'MarcoPay'), ('MARIBANK', 'Maribank'), ('MAYA', 'Maya'), ('MAYBANK', 'Maybank'), ('METROBANK', 'Metrobank'), ('NETBANK', 'Netbank'), ('OWNBANK', 'OwnBank'), ('PALAWAN', 'Palawan'), ('PAYONEER', 'Payoneer'), ('PAYPAL', 'PayPal'), ('PBB', 'PBB'), ('PBCOM', 'PBCOM'), ('PEDDLR', 'Peddlr'), ('PNB', 'PNB'), ('PSBANK', 'PSBank'), ('RAKETPH', 'Raket.ph'), ('RCBC', 'RCBC'), ('SALMON', 'Salmon'), ('SECURITYBANK', 'Security Bank'), ('SHOPBACK', 'ShopBack'), ('SHOPEE', 'Shopee'), ('SINGLIFE', 'Singlife'), ('SKYRO', 'Skyro'), ('SSS', 'SSS'), ('STARBUCKS', 'Starbucks'), ('TALA', 'Tala'), ('TIKTOK', 'TikTok'), ('TONIK', 'Tonik'), ('UNIONBANK', 'UnionBank'), ('UNIONDIGITAL', 'UnionDigital'), ('UNOBANK', 'UNO Bank'), ('VYBE', 'Vybe'), ('WISE', 'Wise'), ('ZED', 'Zed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_category',
            field=models.CharField(choices=[('CASH', 'Cash'), ('SAVINGS', 'Savings'), ('CHECKING', 'Checking'), ('CREDIT', 'Credit'), ('WALLET', 'E-Wallet'), ('INVESTMENT', 'Investment'), ('LOAN', 'Loan'), ('INSURANCE', 'Insurance'), ('PENSION', 'Pension'), ('CRYPTOCURRENCY', 'Cryptocurrency')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('ATOME', 'Atome'), ('AUB', 'AUB'), ('BANKO', 'Banko'), ('BANKOFCOMMERCE', 'Bank of Commerce'), ('BANKOFMAKATI', 'Bank of Makati'), ('BDO', 'BDO'), ('BEEP', 'Beep'), ('BILLEASE', 'BillEase'), ('BPI', 'BPI'), ('CASH', 'Cash'), ('CASHALO', 'Cashalo'), ('CBS', 'CBS'), ('CEBUANA', 'Cebuana'), ('CHINABANK', 'Chinabank'), ('CIMB', 'CIMB'), ('CTBC', 'CTBC'), ('DBP', 'DBP'), ('DISKARTECH', 'DiskarTech'), ('EASTWEST', 'EastWest'), ('FOODPANDA', 'Foodpanda'), ('GCASH', 'GCash'), ('GOTYME', 'GoTyme'), ('GRAB', 'Grab'), ('HELLOMONEY', 'HelloMoney'), ('HOMECREDIT', 'Home Credit'), ('HSBC', 'HSBC'), ('JOYRIDE', 'JoyRide'), ('JUANHAND', 'JuanHand'), ('KOMO', 'Komo'), ('LANDBANK', 'Landbank'), ('LAZADA', 'Lazada'), ('MARCOPAY', 'MarcoPay'), ('MARIBANK', 'Maribank'), ('MAYA', 'Maya'), ('MAYBANK', 'Maybank'), ('METROBANK', 'Metrobank'), ('NETBANK', 'Netbank'), ('OWNBANK', 'OwnBank'), ('PALAWAN', 'Palawan'), ('PAYONEER', 'Payoneer'), ('PAYPAL', 'PayPal'), ('PBB', 'PBB'), ('PBCOM', 'PBCOM'), ('PEDDLR', 'Peddlr'), ('PNB', 'PNB'), ('PSBANK', 'PSBank'), ('RAKETPH', 'Raket.ph'), ('RCBC', 'RCBC'), ('SALMON', 'Salmon'), ('SECURITYBANK', 'Security Bank'), ('SHOPBACK', 'ShopBack'), ('SHOPEE', 'Shopee'), ('SINGLIFE', 'Singlife'), ('SKYRO', 'Skyro'), ('SSS', 'SSS'), ('STARBUCKS', 'Starbucks'), ('TALA', 'Tala'), ('TIKTOK', 'TikTok'), ('TONIK', 'Tonik'), ('UNIONBANK', 'UnionBank'), ('UNIONDIGITAL', 'UnionDigital'), ('UNOBANK', 'UNO Bank'), ('VYBE', 'Vybe'), ('WISE', 'Wise'), ('ZED', 'Zed')], max_length=20),
        ),
    ]
