# Generated by Django 6.0.5 on 2026-05-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_account_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.CharField(choices=[('CASH', 'Cash'), ('SAVINGS', 'Savings'), ('CHECKING', 'Checking'), ('CREDIT', 'Credit'), ('WALLET', 'E-Wallet'), ('INVESTMENT', 'Investment'), ('LOAN', 'Loan'), ('INSURANCE', 'Insurance'), ('PENSION', 'Pension'), ('CRYPTOCURRENCY', 'Cryptocurrency')], max_length=20),
        ),
    ]
