# Generated by Django 6.0.5 on 2026-05-08 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_account_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account_category',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.account'),
            preserve_default=False,
        ),
    ]
