# Generated by Django 6.0.5 on 2026-05-08 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_transaction_account_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='account_id',
            new_name='account',
        ),
    ]
