// export const brands: Record<string, any> = {
//   "ATOME": require("../../assets/accounts/atome.png"),
//   "AUB": require("../../assets/accounts/aub.png"),
//   "BANKO": require("../../assets/accounts/banko.png"),
//   "BANKOFCOMMERCE": require("../../assets/accounts/bankofcommerce.png"),
//   "BANKOFMAKATI": require("../../assets/accounts/bankofmakati.png"),
//   "BDO": require("../../assets/accounts/bdo.png"),
//   "BEEP": require("../../assets/accounts/beep.png"),
//   "BILLEASE": require("../../assets/accounts/billease.png"),
//   "BPI": require("../../assets/accounts/bpi.png"),
//   "CASH": require("../../assets/accounts/cash.png"),
//   "CASHALO": require("../../assets/accounts/cashalo.png"),
//   "CBS": require("../../assets/accounts/cbs.png"),
//   "CEBUANA": require("../../assets/accounts/cebuana.png"),
//   "CHINABANK": require("../../assets/accounts/chinabank.png"),
//   "CIMB": require("../../assets/accounts/cimb.png"),
//   "CTBC": require("../../assets/accounts/ctbc.png"),
//   "DBP": require("../../assets/accounts/dbp.png"),
//   "DISKARTECH": require("../../assets/accounts/diskartech.png"),
//   "EASTWEST": require("../../assets/accounts/eastwest.png"),
//   "FOODPANDA": require("../../assets/accounts/foodpanda.png"),
//   "GCASH": require("../../assets/accounts/gcash.png"),
//   "GOTYME": require("../../assets/accounts/gotyme.png"),
//   "GRAB": require("../../assets/accounts/grab.png"),
//   "HELLOMONEY": require("../../assets/accounts/hellomoney.png"),
//   "HOMECREDIT": require("../../assets/accounts/homecredit.png"),
//   "HSBC": require("../../assets/accounts/hsbc.png"),
//   "JOYRIDE": require("../../assets/accounts/joyride.png"),
//   "JUANHAND": require("../../assets/accounts/juanhand.png"),
//   "KOMO": require("../../assets/accounts/komo.png"),
//   "LANDBANK": require("../../assets/accounts/landbank.png"),
//   "LAZADA": require("../../assets/accounts/lazada.png"),
//   "MARCOPAY": require("../../assets/accounts/marcopay.png"),
//   "MARIBANK": require("../../assets/accounts/maribank.png"),
//   "MAYA": require("../../assets/accounts/maya.png"),
//   "MAYBANK": require("../../assets/accounts/maybank.png"),
//   "METROBANK": require("../../assets/accounts/metrobank.png"),
//   "NETBANK": require("../../assets/accounts/netbank.png"),
//   "OWNBANK": require("../../assets/accounts/ownbank.png"),
//   "PALAWAN": require("../../assets/accounts/palawan.png"),
//   "PAYONEER": require("../../assets/accounts/payoneer.png"),
//   "PAYPAL": require("../../assets/accounts/paypal.png"),
//   "PBB": require("../../assets/accounts/pbb.png"),
//   "PBCOM": require("../../assets/accounts/pbcom.png"),
//   "PEDDLR": require("../../assets/accounts/peddlr.png"),
//   "PNB": require("../../assets/accounts/pnb.png"),
//   "PSBANK": require("../../assets/accounts/psbank.png"),
//   "RAKETPH": require("../../assets/accounts/raketph.png"),
//   "RCBC": require("../../assets/accounts/rcbc.png"),
//   "SALMON": require("../../assets/accounts/salmon.png"),
//   "SECURITYBANK": require("../../assets/accounts/securitybank.png"),
//   "SHOPBACK": require("../../assets/accounts/shopback.png"),
//   "SHOPEE": require("../../assets/accounts/shopee.png"),
//   "SINGLIFE": require("../../assets/accounts/singlife.png"),
//   "SKYRO": require("../../assets/accounts/skyro.png"),
//   "SSS": require("../../assets/accounts/sss.png"),
//   "STARBUCKS": require("../../assets/accounts/starbucks.png"),
//   "TALA": require("../../assets/accounts/tala.png"),
//   "TIKTOK": require("../../assets/accounts/tiktok.png"),
//   "TONIK": require("../../assets/accounts/tonik.png"),
//   "UNIONBANK": require("../../assets/accounts/unionbank.png"),
//   "UNIONDIGITAL": require("../../assets/accounts/uniondigital.png"),
//   "UNOBANK": require("../../assets/accounts/unobank.png"),
//   "VYBE": require("../../assets/accounts/vybe.png"),
//   "WISE": require("../../assets/accounts/wise.png"),
//   "ZED": require("../../assets/accounts/zed.png"),
// };

export const brands: Record<string, any> = {
  atome: require("../../assets/accounts/atome.png"),
  aub: require("../../assets/accounts/aub.png"),
  banko: require("../../assets/accounts/banko.png"),
  bankofcommerce: require("../../assets/accounts/bankofcommerce.png"),
  bankofmakati: require("../../assets/accounts/bankofmakati.png"),
  bdo: require("../../assets/accounts/bdo.png"),
  beep: require("../../assets/accounts/beep.png"),
  billease: require("../../assets/accounts/billease.png"),
  bpi: require("../../assets/accounts/bpi.png"),
  cash: require("../../assets/accounts/cash.png"),
  cashalo: require("../../assets/accounts/cashalo.png"),
  cbs: require("../../assets/accounts/cbs.png"),
  cebuana: require("../../assets/accounts/cebuana.png"),
  chinabank: require("../../assets/accounts/chinabank.png"),
  cimb: require("../../assets/accounts/cimb.png"),
  ctbc: require("../../assets/accounts/ctbc.png"),
  dbp: require("../../assets/accounts/dbp.png"),
  diskartech: require("../../assets/accounts/diskartech.png"),
  eastwest: require("../../assets/accounts/eastwest.png"),
  foodpanda: require("../../assets/accounts/foodpanda.png"),
  gcash: require("../../assets/accounts/gcash.png"),
  gotyme: require("../../assets/accounts/gotyme.png"),
  grab: require("../../assets/accounts/grab.png"),
  hellomoney: require("../../assets/accounts/hellomoney.png"),
  homecredit: require("../../assets/accounts/homecredit.png"),
  hsbc: require("../../assets/accounts/hsbc.png"),
  joyride: require("../../assets/accounts/joyride.png"),
  juanhand: require("../../assets/accounts/juanhand.png"),
  komo: require("../../assets/accounts/komo.png"),
  landbank: require("../../assets/accounts/landbank.png"),
  lazada: require("../../assets/accounts/lazada.png"),
  marcopay: require("../../assets/accounts/marcopay.png"),
  maribank: require("../../assets/accounts/maribank.png"),
  maya: require("../../assets/accounts/maya.png"),
  maybank: require("../../assets/accounts/maybank.png"),
  metrobank: require("../../assets/accounts/metrobank.png"),
  netbank: require("../../assets/accounts/netbank.png"),
  ownbank: require("../../assets/accounts/ownbank.png"),
  palawan: require("../../assets/accounts/palawan.png"),
  payoneer: require("../../assets/accounts/payoneer.png"),
  paypal: require("../../assets/accounts/paypal.png"),
  pbb: require("../../assets/accounts/pbb.png"),
  pbcom: require("../../assets/accounts/pbcom.png"),
  peddlr: require("../../assets/accounts/peddlr.png"),
  pnb: require("../../assets/accounts/pnb.png"),
  psbank: require("../../assets/accounts/psbank.png"),
  raketph: require("../../assets/accounts/raketph.png"),
  rcbc: require("../../assets/accounts/rcbc.png"),
  salmon: require("../../assets/accounts/salmon.png"),
  securitybank: require("../../assets/accounts/securitybank.png"),
  shopback: require("../../assets/accounts/shopback.png"),
  shopee: require("../../assets/accounts/shopee.png"),
  singlife: require("../../assets/accounts/singlife.png"),
  skyro: require("../../assets/accounts/skyro.png"),
  sss: require("../../assets/accounts/sss.png"),
  starbucks: require("../../assets/accounts/starbucks.png"),
  tala: require("../../assets/accounts/tala.png"),
  tiktok: require("../../assets/accounts/tiktok.png"),
  tonik: require("../../assets/accounts/tonik.png"),
  unionbank: require("../../assets/accounts/unionbank.png"),
  uniondigital: require("../../assets/accounts/uniondigital.png"),
  unobank: require("../../assets/accounts/unobank.png"),
  vybe: require("../../assets/accounts/vybe.png"),
  wise: require("../../assets/accounts/wise.png"),
  zed: require("../../assets/accounts/zed.png"),
};

